import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { WalletsProvider } from '@/providers/wallets';
import './globals.css';

export const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Dapp',
  description: 'Generated by create dapp cli',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <WalletsProvider>{children}</WalletsProvider>
      </body>
    </html>
  );
}
